// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '/',
    appId: '1:622161860190:web:7fdff01610c2b54be686cf',
    messagingSenderId: '622161860190',
    projectId: 'multion-project-b9754',
    authDomain: 'multion-project-b9754.firebaseapp.com',
    storageBucket: 'multion-project-b9754.appspot.com',
    measurementId: 'G-KDGFJ9F09J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '/',
    appId: '1:622161860190:android:c2829c51c0f6e4a6e686cf',
    messagingSenderId: '622161860190',
    projectId: 'multion-project-b9754',
    storageBucket: 'multion-project-b9754.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '/',
    appId: '1:622161860190:ios:8b335601089c4267e686cf',
    messagingSenderId: '622161860190',
    projectId: 'multion-project-b9754',
    storageBucket: 'multion-project-b9754.appspot.com',
    iosBundleId: 'com.example.multionProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '/',
    appId: '1:622161860190:ios:8b335601089c4267e686cf',
    messagingSenderId: '622161860190',
    projectId: 'multion-project-b9754',
    storageBucket: 'multion-project-b9754.appspot.com',
    iosBundleId: 'com.example.multionProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '/',
    appId: '1:622161860190:web:acb79d6792d9a7cae686cf',
    messagingSenderId: '622161860190',
    projectId: 'multion-project-b9754',
    authDomain: 'multion-project-b9754.firebaseapp.com',
    storageBucket: 'multion-project-b9754.appspot.com',
    measurementId: 'G-NME65D6FDR',
  );

}